#OBD Modes (described in OBD-II standard SAE J1979)
CURRENT_DATA = "01"
FREEZE_FRAME_DATA = "02"
REQUEST_TROUBLE_CODES = "03"
CLEAR_TROUBLE_CODES_AND_VALUES = "04"
OXYGEN_SENSOR_DATA = "05"
SYSTEM_MONITORING_DATA = "06"
PENDING_TROUBLE_CODES = "07"
CONTROL_OPERATION = "08"
VEHICLE_INFORMATION_DATA = "09"
PERMANENT_TROUBLE_CODES = "0A"

DEFAULT_OBD_MODE = CURRENT_DATA
